import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
const API='http://localhost:8000';
function normalizeEquation(text=''){return String(text).replace(/<->|⇄|↔|⇌/g,'⇌').replace(/=>|->|⟶|→/g,'→').replace(/[;,.:\s]+$/g,'').trim();}
function App(){const[file,setFile]=useState(null);const[job,setJob]=useState(null);const[items,setItems]=useState([]);const[selected,setSelected]=useState({});const[busy,setBusy]=useState(false);const[err,setErr]=useState('');async function upload(e){e?.preventDefault();setErr('');if(!file){setErr('Выбери PDF-файл');return;}try{setBusy(true);const form=new FormData();form.append('file',file);const res=await fetch(`${API}/agent/upload`,{method:'POST',body:form});if(!res.ok)throw new Error(await res.text());const j=await res.json();setJob(j);setItems([]);setSelected({});}catch(ex){setErr('Ошибка загрузки PDF: '+ex.message);}finally{setBusy(false);}}
async function load(){if(!job?.id)return;try{const j=await fetch(`${API}/agent/jobs/${job.id}`).then(r=>r.json());const rs=await fetch(`${API}/agent/jobs/${job.id}/reactions`).then(r=>r.json()).catch(()=>[]);setJob(j);setItems(Array.isArray(rs)?rs:[]);setSelected(prev=>{const n={...prev};(Array.isArray(rs)?rs:[]).forEach(x=>{if(n[x.id]===undefined)n[x.id]=x.selected!==false});return n;});}catch(e){setErr('Ошибка обновления статуса: '+e.message)}}
useEffect(()=>{if(!job?.id)return;load();const t=setInterval(load,1500);return()=>clearInterval(t)},[job?.id]);
function upd(i,k,v){const a=[...items];a[i]={...a[i],[k]:k==='equation'?normalizeEquation(v):v};setItems(a);}async function save(r){await fetch(`${API}/agent/job-reactions/${r.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...r,equation:normalizeEquation(r.equation),selected:selected[r.id]??true})});await load();}async function publish(ids){const clean=ids.filter(Boolean);if(!clean.length)return alert('Не выбраны реакции');await fetch(`${API}/agent/publish`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(clean)});alert('Реакции отправлены на сайт');await load();}
return <main className="page"><section className="card"><h1>AI-агент обработки PDF</h1><form onSubmit={upload} className="upload"><input type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><button type="submit" disabled={busy}>{busy?'Загрузка...':'Загрузить PDF'}</button></form>{err&&<p className="error">{err}</p>}{job&&<div><h2>Прогресс</h2><p>{job.status}: {job.message}</p><progress value={job.progress_percent||0} max="100"/><p>{job.progress_percent||0}% · страниц: {job.processed_pages||0}/{job.total_pages||0} · найдено: {items.length}</p></div>}</section>{items.length>0&&<section className="card"><h2>Извлечённые реакции</h2><button onClick={()=>publish(items.filter(x=>selected[x.id]).map(x=>x.id))}>Загрузить выбранные</button><button onClick={()=>publish(items.map(x=>x.id))}>Загрузить все</button>{items.map((r,i)=><article className={`reaction ${r.internet_status==='does_not_react'?'negative':''}`} key={r.id}><label><input type="checkbox" checked={!!selected[r.id]} onChange={e=>setSelected({...selected,[r.id]:e.target.checked})}/> выбрать</label>{r.internet_status==='does_not_react'&&<p className="warn">Отрицательная реакция: будет скрыта из каталога, но доступна через поиск.</p>}<input value={r.reaction_name||''} onChange={e=>upd(i,'reaction_name',e.target.value)} placeholder="Название реакции"/><textarea value={r.equation||''} onChange={e=>upd(i,'equation',e.target.value)} placeholder="Уравнение"/><div className="grid"><input value={r.temperature||''} onChange={e=>upd(i,'temperature',e.target.value)} placeholder="Температура"/><input value={r.catalysts||''} onChange={e=>upd(i,'catalysts',e.target.value)} placeholder="Катализаторы"/><input value={r.conditions||''} onChange={e=>upd(i,'conditions',e.target.value)} placeholder="Условия над стрелкой"/><input value={r.pressure||''} onChange={e=>upd(i,'pressure',e.target.value)} placeholder="Давление"/></div><button onClick={()=>save(r)}>Сохранить правки</button><button onClick={()=>publish([r.id])}>Загрузить эту реакцию</button></article>)}</section>}</main>}
createRoot(document.getElementById('root')).render(<App/>);
